In [1]:
from transformers import DistilBertTokenizer, DistilBertModel, DistilBertForMaskedLM, DistilBertConfig
from transformers import BertTokenizer, BertModel, BertConfig

import torch
import numpy as np

import pickle
from tqdm import tqdm

from collections import Counter
import matplotlib.pyplot as plt

import logging
logging.getLogger("transformers.tokenization_utils").setLevel(logging.ERROR)

I0224 17:50:37.951418 140613445986112 file_utils.py:38] PyTorch version 1.4.0 available.


In [2]:
with open("emails_token_ids.pkl", "rb") as handle:
    ids = pickle.load(handle)

In [24]:
first = ids[0]

print(first.shape[-1])

172


In [22]:
n = 512
k = 20

l = 738


# (0, n), (n-k, n-k+n=2n-k), ()


# (0, 512=1*512-0*20), ((512-20), (512-20)+512=2*512-20), (2*512-20-20=2*512-2*20, )


def cut_up_overlap(tens, n=512, k=20):
    l = tens.shape[-1]
    
    if l < n:
        return [tens]
    
    for 
    
    




n = 5
k = 2
l 

cut_up_overlap = []


for i in range(4):    
    print(
        (i*n)-(i*k),
        ((i+1)*n)-(i*k)
    )
    
    print(list(range((i*n)-(i*k),
        ((i+1)*n)-(i*k))))
    
    print()
    



# [(i, (i+1)*n) for i]

0 5
[0, 1, 2, 3, 4]

3 8
[3, 4, 5, 6, 7]

6 11
[6, 7, 8, 9, 10]

9 14
[9, 10, 11, 12, 13]



In [39]:
n = 511
k = 20

l = 718

x = torch.arange(0, l)

unfd = x.unfold(0, n, n-k)

got = unfd.shape[0]*unfd.shape[1] - unfd.shape[0]*(k)

last = x[got:]

tuple(v for v in unfd)+ (last,)

(tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
         140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 173, 174, 175, 176

In [35]:
511+227

738

In [38]:
x.split(511)

(tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
         140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 173, 174, 175, 176

In [13]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertForMaskedLM.from_pretrained('distilbert-base-uncased')

model.eval()

with torch.no_grad():
    input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
    outputs = model(input_ids, masked_lm_labels=input_ids)
    loss, prediction_scores = outputs[:2]

I0224 14:33:43.350871 139634746525504 configuration_utils.py:254] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-config.json from cache at /home/valentin/.cache/torch/transformers/a41e817d5c0743e29e86ff85edc8c257e61bc8d88e4271bb1b243b6e7614c633.587f67ec28c540f4294c9c2ac7dcf7841ff371aeb12cdeb6a17f69da39ad9452
I0224 14:33:43.354784 139634746525504 configuration_utils.py:290] Model config DistilBertConfig {
  "activation": "gelu",
  "architectures": [
    "DistilBertForMaskedLM"
  ],
  "attention_dropout": 0.1,
  "bos_token_id": 0,
  "dim": 768,
  "do_sample": false,
  "dropout": 0.1,
  "eos_token_ids": 0,
  "finetuning_task": null,
  "hidden_dim": 3072,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_he

In [10]:
print(loss)

tensor(5.0893, grad_fn=<NllLossBackward>)


In [19]:
print(input_ids.shape), print(prediction_scores.shape)

torch.softmax(prediction_scores, 2, torch.float64).

torch.Size([1, 8])
torch.Size([1, 8, 30522])


tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000]],
       dtype=torch.float64)